### ISSUE TITLE
Exceptions in console

### ISSUE THREAD

**Issue by bizoo** [tanepiper/sublime-todomanager#1]
Hi,

I have a bunch of this message in my console:
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 175, in on_load
  File ".\sublime_plugin.py", line 154, in run_timed_function
  File ".\sublime_plugin.py", line 174, in <lambda>
  File ".\TodoManager.py", line 480, in on_load
  File ".\TodoManager.py", line 65, in **init**
AttributeError: 'NoneType' object has no attribute 'split'

I suppose it's caused by buffer that don't have a filename (new unsaved file or maybe console).

**Comment by tanepiper** [comment]
Ahh indeed, when I do it I get errors with no windows and with untitled windows - I'll need to add a check in here that there is a valid view.  Thanks, I'll get on that for the next release

**Comment by tanepiper** [comment]
Now fixed in 1.1.10
